### ISSUE TITLE
Multiplatform ?

### ISSUE THREAD

**Issue by dhakehurst** [ufoscout/properlty#17]
Any thoughts about an mpp version ?

**Comment by ufoscout** [comment]
@dhakehurst 
could you please provide more details about your idea? What do you mean by "multiplatform" exactly? 
What is missing to make it multiplatform?

**Comment by dhakehurst** [comment]
https://kotlinlang.org/docs/reference/multiplatform.html

**Comment by ufoscout** [comment]
@dhakehurst 
please provide a clear use case or send a PR, this is too generic to be actionable.

**Comment by ufoscout** [comment]
I am closing it as there are no actionable tasks based on the provided input.
